assembly2:
        cl assembly2.c

assembly3:
        cl assembly3.c
		assembly3
		
testApp:
       cl testApp.c
	   testApp
	   
helloworld: 
       cl helloworld.c
	   cl /c /Fa helloworld.c
	   helloworld
	 
helloworldonecall: 
       cl helloworldonecall.c
	   cl /c /Fa helloworldonecall.c
	   helloworldonecall
	   
function: 
       cl function.c
	   cl /c /Fa function.c
	   function
	   
exercise3:
        cl exercise3.c
		cl /c /Fa exercise3.c
		exercise3

ex4:
  cl ex4.c  
  cl /c /Fa ex4.c
  ex4
		
		
clean:
     del *.obj
	 del *.exe
	 del *.asm
